# Generated by Django 4.0.1 on 2022-01-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20200311_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Covid_19', models.CharField(max_length=30)),
                ('Cold', models.CharField(max_length=30)),
                ('Flu', models.CharField(max_length=30)),
                ('Asthma', models.CharField(max_length=30)),
                ('Lung_cancer', models.CharField(max_length=30)),
                ('Epilepsy', models.CharField(max_length=30)),
                ('Pneumonia', models.CharField(max_length=30)),
                ('Rabies', models.CharField(max_length=30)),
                ('Diabetes', models.CharField(max_length=30)),
                ('Food_poisoning', models.CharField(max_length=30)),
                ('Allergies', models.CharField(max_length=30)),
                ('Heart_failure', models.CharField(max_length=30)),
                ('Bladder_cancer', models.CharField(max_length=30)),
                ('Bone_cancer', models.CharField(max_length=30)),
                ('Gingivitis', models.CharField(max_length=30)),
                ('Kidney_stone', models.CharField(max_length=30)),
                ('High_blood_pressure', models.CharField(max_length=30)),
                ('Anemia', models.CharField(max_length=30)),
                ('Hemorrhagic_fevers', models.CharField(max_length=30)),
                ('Norovirus_infection', models.CharField(max_length=30)),
                ('Chronic_kidney_disease', models.CharField(max_length=30)),
                ('Rotavirus_infection', models.CharField(max_length=30)),
                ('Fatty_liver', models.CharField(max_length=30)),
                ('Dengue', models.CharField(max_length=30)),
                ('Osteoporosis', models.CharField(max_length=30)),
                ('Fibromyalgia', models.CharField(max_length=30)),
                ('Meningitis', models.CharField(max_length=30)),
                ('E_coli', models.CharField(max_length=30)),
                ('Pink_eye', models.CharField(max_length=30)),
                ('Salmonella_infection', models.CharField(max_length=30)),
                ('Malaria', models.CharField(max_length=30)),
                ('Tuberculosis', models.CharField(max_length=30)),
                ('Scarlet_fever', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'disease_lists',
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'travello_lists',
            },
        ),
    ]
