# Generated by Django 4.0.1 on 2022-01-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_symptomps_list_title_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomps_list',
            name='symptomps',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
