# Generated by Django 4.0.1 on 2022-01-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_disease_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation_treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('explanation', models.TextField()),
                ('treatment', models.TextField()),
            ],
            options={
                'db_table': 'explanation_treatment',
            },
        ),
    ]
