# Generated by Django 3.2.11 on 2022-02-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=30)),
                ('lastName', models.TextField(max_length=30)),
                ('moblieNumber', models.TextField(max_length=30)),
                ('interests', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=30)),
                ('websiteURL', models.TextField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'admin_profile',
            },
        ),
    ]
